# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: 安装依赖
              run: echo hello

    build:
        # strategy:
        #     matrix:
        #         version: [10, 12, 14]
        #         os: [ubuntu-latest, windows-latest]
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: 打包
              run: echo hello

    deploy:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: 部署
              run: echo hello

    publish:
        runs-on: ubuntu-latest
        needs:
            - build
            - deploy
        environment: publish
        steps:
            - name: 发布
              run: echo hello
