# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: echo hello

    test:
        strategy:
            matrix:
                version: [10, 12, 14]
                os: [ubuntu-latest, windows-latest]
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: build
              run: echo hello

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: build
              run: echo hello

    publish:
        runs-on: ubuntu-latest
        needs:
            - test
            - deploy
        environment: publish
        steps:
            - name: build
              run: echo hello
